example/urls.py
from django.conf.urls import patterns, url

import example.views

urlpatterns = patterns('',
    # Examples:
    url(r'^$', example.views.index, name='example-index'),
)

fancymail/models.py
from django.db import models

# Create your models here.

example/forms.py
from django import forms


CHOICES = [('template1', 'Template 1'),
          ('template2', 'Template 2')]


class MailForm(forms.Form):
    template = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    subject = forms.CharField(max_length=200, label=u'Subject')
    to = forms.EmailField(max_length=200, label=u'To')
    from_email = forms.EmailField(max_length=200, label=u'From')
    password = forms.CharField(widget=forms.PasswordInput(render_value=False),
                                max_length=50, label=u'Password')

    context_user = forms.CharField(max_length=50, label=u'Personalized name')

    email_host = forms.CharField(max_length=50, label=u'Email host')
    email_port = forms.IntegerField(label=u'Email port')
    use_tls = forms.BooleanField(label=u'Use TLS', initial=False, required=False)
    use_gmail = forms.BooleanField(label=u'Use Gmail settings', initial=False, required=False)

example/views.py
from django.conf import settings
from django.shortcuts import render_to_response, RequestContext
from django.contrib import messages
from fancymail.mail import FancyMail

from example.forms import MailForm


def index(request):

    if request.method == 'POST':
        form = MailForm(request.POST)
        if form.is_valid():

            #Create the email
            msg = FancyMail()
            msg.subject = form.cleaned_data['subject']
            msg.to = [form.cleaned_data['to'], ]
            msg.from_email = form.cleaned_data['from_email']
            password = form.cleaned_data['password']
            use_tls = form.cleaned_data['use_tls']
            email_host = form.cleaned_data['email_host']
            email_port = form.cleaned_data['email_port']

            # Set Django live settings (Do not do this in production!!!!)
            settings.EMAIL_HOST_USER = msg.from_email
            settings.EMAIL_HOST_PASSWORD = password
            settings.EMAIL_USE_TLS = use_tls
            settings.EMAIL_HOST = email_host
            settings.EMAIL_PORT = email_port

            #Set context
            context = {
                    'user': form.cleaned_data['context_user']
            }

            # Load templates
            template = form.cleaned_data['template']
            msg.load_template("email/{0}/welcome.html".format(template),
                                context)
            # Send!
            msg.send()

            messages.success(request,
                    "Mail sent to {0} ".format(context['user']))
    else:
        form = MailForm()

    data = {
        'mail_form': form,
    }

    return render_to_response('example/index.html',
                            data,
                            context_instance=RequestContext(request))

fancymail/views.py
# Create your views here.

example/templates/example/base.html
<html>
    <head>
        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <style type="text/css">
            ul
            {
                list-style-type: none;
            }
        </style>
    </head>
    <body>
    <div class="container">
    {% block body %}
    {% endblock body %}
    </div>
    </body>
</html>

example/templates/example/index.html
{% extends "example/base.html" %}
{% block body %}
    
    <script>
        var use_tls = null;
        var email_port = null;
        var email_host = null;

        $(document).on('click', '#id_use_gmail', function() {
            var $this = $(this);   
            if ($this.is(':checked')) {
                // Save previous data
                use_tls = $('#id_use_tls').is(':checked');
                email_port = $('#id_email_port').val();
                email_host = $('#id_email_host').val();

                // set gmail data
                $('#id_use_tls').attr('checked', true);
                $('#id_email_port').val(587);
                $('#id_email_host').val('smtp.gmail.com');

                //disable forms
                $('#id_use_tls').attr('readonly', true);
                $('#id_email_port').attr('readonly', true);
                $('#id_email_host').attr('readonly', true);

            } else {
                // recover the values
                $('#id_use_tls').attr('checked', use_tls);
                $('#id_email_port').val(email_port);
                $('#id_email_host').val(email_host);

                //enable again
                $('#id_use_tls').removeAttr('readonly');
                $('#id_email_port').removeAttr('readonly');
                $('#id_email_host').removeAttr('readonly');
            }
        });
    </script> 

    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}
    <h1>Send a testing Email with Django Fancymail</h1>
    <div class="alert alert-block">
        <h3>
            Doesn't log or save the sent emails, email address or passwords.
            <a href="https://github.com/slok/django-fancymail/blob/master/example/views.py">Check the code! :)</a>
        </h3>
    </div>
    <div class="well">
     <form id="mail_form" class="form-horizontal" action="" method="post">{% csrf_token %}
        {% if mail_form.non_field_errors %}
        <div class="alert alert-error">
            {{ mail_form.non_field_errors }}
        </div>
        {% endif %}
        <div class="alert alert-info">
             <h3>Email settings</h3>
            
            {% if mail_form.subject.errors %}
            <div class="alert alert-error">{{ mail_form.subject.errors }}</div>
            {% endif %}

             <div class="control-group">
                {{ mail_form.subject.label_tag }}
                <div class="controls">
                    {{ mail_form.subject }}
                </div>
            </div>

            {% if mail_form.to.errors %}
            <div class="alert alert-error">{{ mail_form.to.errors }}</div>
            {% endif %}

             <div class="control-group">
                {{ mail_form.to.label_tag }}
                <div class="controls">
                    {{ mail_form.to }}
                </div>
            </div>

            {% if mail_form.from_email.errors %}
            <div class="alert alert-error">{{ mail_form.from_email.errors }}</div>
            {% endif %}
            
             <div class="control-group">
                {{ mail_form.from_email.label_tag }}
                <div class="controls">
                    {{ mail_form.from_email }}
                </div>
            </div>
           
            {% if mail_form.password.errors %}
            <div class="alert alert-error">{{ mail_form.password.errors }}</div>
            {% endif %}

             <div class="control-group">
                {{ mail_form.password.label_tag }}
                <div class="controls">
                    {{ mail_form.password }}
                </div>
            </div>
        </div>

        <div class="alert alert-info">
            <h3>Template settings</h3>
            <div class="radio">
                {{ mail_form.template.label_tag }}
                <div class="controls">
                    {{ mail_form.template }}
                </div>
            </div>

            {% if mail_form.context_user.errors %}
            <div class="alert alert-error">{{ mail_form.context_user.errors }}</div>
            {% endif %}

            <div class="control-group">
            {{ mail_form.context_user.label_tag }}
            <div class="controls">
                {{ mail_form.context_user }}
            </div>
        </div>

        </div>
        <div class="alert alert-info">
            <h3>Email host settings</h3>
            <div class="checkbox">
                {{ mail_form.use_gmail.label_tag }}
                <div class="controls">
                    {{ mail_form.use_gmail }}
                </div>
            </div>
            <div class="checkbox">
                {{ mail_form.use_tls.label_tag }}
                <div class="controls">
                    {{ mail_form.use_tls }}
                </div>
            </div>

            {% if mail_form.email_host.errors %}
            <div class="alert alert-error">{{ mail_form.email_host.errors }}</div>
            {% endif %}

            <div class="control-group">
                {{ mail_form.email_host.label_tag }}
                <div class="controls">
                    {{ mail_form.email_host }}
                </div>
            </div>

            {% if mail_form.email_port.errors %}
                <div class="alert alert-error">{{ mail_form.email_port.errors }}</div>
            {% endif %}

            <div class="control-group">
                {{ mail_form.email_port.label_tag }}
                <div class="controls">
                    {{ mail_form.email_port }}
                </div>
            </div>

        </div>


        <button class="btn btn-primary" type="submit">Send templated email!</button>
    </form>

    </div>

{% endblock body %}